model:
  swinir:
    target: sgip.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

dataset:
  train:
    target: sgip.dataset.sgip_dataset.DatasetPair
    params:
      # training file list path
      file_list: /root/autodl-tmp/project/SGIP-dev-v2/data_json/PIE_clean_s1expos_train.json
      file_backend_cfg:
        target: sgip.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: none
      gt_path: /root/autodl-tmp/dataset/DATA/MTPIE/train_val_split/train/gt_expos
  val:
    target: sgip.dataset.sgip_dataset.DatasetPair
    params:
      # validation file list path
      file_list: /root/autodl-tmp/project/SGIP-dev-v2/data_json/PIE_clean_s1expos_val.json
      file_backend_cfg:
        target: sgip.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: none
      gt_path: /root/autodl-tmp/dataset/DATA/MTPIE/train_val_split/val/gt_expos

batch_transform:
  target: sgip.dataset.batch_transform.IdentityBatchTransform

train:
  # experiment directory path
  exp_dir: /root/autodl-tmp/project/SGIP-dev-v2/work_dirs/train_stage1_base
  learning_rate: 5e-5
  # total batch size
  batch_size: 8
  num_workers: 8
  train_steps: 200000
  log_every: 5000
  ckpt_every: 20000
  image_every: 20000
  val_every: 20000
  resume: /root/autodl-tmp/project/SGIP-dev-v2/work_dirs/train_stage1_base/checkpoints/0080000.pt
