model:
  cldm:
    target: sgip.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 64 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 64 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  swinir:
    target: sgip.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  diffusion:
    target: sgip.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: False
      parameterization: eps

dataset:
  train:
    target: sgip.dataset.sgip_dataset.SgipDataset
    params:
      # training file list path
      file_list: /root/autodl-tmp/project/SGIP-dev-v2/prepare_data/swinir_s1_p0195/PIE_swinir_s1_p0195_train.json
      file_backend_cfg:
        target: sgip.dataset.file_backend.HardDiskBackend
      out_size: 64  # stage1 input 64; stage2 input 512
      crop_type: none
  val:
    target: sgip.dataset.sgip_dataset.SgipDataset
    params:
      # training file list path
      file_list: /root/autodl-tmp/project/SGIP-dev-v2/prepare_data/swinir_s1_p0195/PIE_swinir_s1_p0195_val.json
      file_backend_cfg:
        target: sgip.dataset.file_backend.HardDiskBackend
      out_size: 64  # stage1 input 64; stage2 input 512
      crop_type: none
  

batch_transform:
  target: sgip.dataset.batch_transform.IdentityBatchTransform

train:
  # pretrained sd v2.1 path
  sd_path: /root/autodl-tmp/project/SGIP-dev-v2/weights/v2-1_512-ema-pruned.ckpt
  # experiment directory path
  exp_dir: /root/autodl-tmp/project/SGIP-dev-v2/work_dirs/train_stage2_base_fr_0401
  # stage 1 swinir path.
  # In our paper, we use SwinIR trained on ImageNet-1k with codeformer degradation.
  swinir_path: ~
  learning_rate: 1e-4
  # ImageNet 1k (1.3M images)
  # batch size = 192, lr = 1e-4, total training steps = 25k
  # Our filtered laion2b-en (15M images)
  # batch size = 256, lr = 1e-4 (first 30k), 1e-5 (next 50k), total training steps = 80k
  batch_size: 8
  num_workers: 8
  train_steps: 63000
  log_every: 500
  ckpt_every: 10440
  image_every: 104400
  val_every: 10440
  resume: ~
  noise_aug_timestep: 0
  load_clean: True